### ISSUE TITLE
fix: File not found - should return 404 instead of 500 in the /summary endpoint

### ISSUE THREAD

**Issue by yassinrais** [saferwall/saferwall-api#11]
### Example :

1. https://api.saferwall.com/v1/files/51caae41376b1b031ff6e35c9180eae57d702a44538942e01a33b86afdcd985d
```json
{
  "status": 404,
  "message": "The requested resource was not found."
}
```

2. https://api.saferwall.com/v1/files/51caae41376b1b031ff6e35c9180eae57d702a44538942e01a33b86afdcd985d/summary
```json
{
  "status": 500,
  "message": "We encountered an error while processing your request."
}
```

### Expected:
**(2)**  response should be same as **(1)** response
```json
{
  "status": 404,
  "message": "The requested resource was not found."
}
```

**Comment by LordNoteworthy** [comment]
Yeah, thanks for openning this one as I have this problem in many endpoints.

**Comment by LordNoteworthy** [comment]
4298731696de0ad3704ca65c54fffe8ffa7c660f
