### ISSUE TITLE
Log in using email or username

### ISSUE THREAD

**Issue by yassinrais** [saferwall/saferwall-api#31]
I just noticed that we can only log in using username. 

Is there a reason we don't allow logins using the email address?

https://github.com/saferwall/saferwall-api/blob/ae4f7c08de4c706c840f559b53502be0ced6ab87/internal/auth/service.go#L84

**Comment by LordNoteworthy** [comment]
Oh yeah, I will add that. Thanks.

**Comment by LordNoteworthy** [comment]
✅ releasing it in a minute.

**Comment by LordNoteworthy** [comment]
ok, /live

**Comment by yassinrais** [comment]
Login response should contains username of the user in case of email login 😄

**Comment by LordNoteworthy** [comment]
hahaha ok :)
