### ISSUE TITLE
hard code max file size 

### ISSUE THREAD

**Issue by kid0604** [saferwall/saferwall-api#35]
![image](https://user-images.githubusercontent.com/9206144/236773841-9b4ca661-ff41-4599-ad25-92351bef285d.png)

I tried to increase the max upload file size but it didn't work. Looks like it was hardcoded in the api.go . file [](https://github.com/saferwall/saferwall-api/blob/81fad8ddec03d7f730e203442debb459745a6eca/internal/file/api.go#L124)

**Comment by LordNoteworthy** [comment]
Hello @kid0604 

I can externalize that hardcoded values, I will create a PR soon.

**Comment by LordNoteworthy** [comment]
Fixed. Look at the config file, it has a field called max_file_size that is expressed in MB, by default it is 64, you can set it to a higher value. But that also mean, you might need to increase the `scan-timeout` in each AV because scanning large files might require more time.
